File: /prometheus/alert.rules; Group name: alert.rules.yml
-------
alert: service_down
expr: up == 0
for: 5m
annotations:
  host: '{{ $labels.instance }}'
  summary: '{{ $labels.job }} instance is down'
-------

# groups:
#   - name: alert.rules
#     rules:
#     - alert: InstanceDown
#       expr: up == 0
#       for: 1m
#       labels:
#         severity: page
#       annotations:
#         description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
#         summary: 'Instance {{ $labels.instance }} down'
